"""empty message

Revision ID: 04028ec6a9c8
Revises: fb26834b5b2e
Create Date: 2023-09-18 13:01:19.184814

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '04028ec6a9c8'
down_revision = 'fb26834b5b2e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('_alembic_tmp_book')
    with op.batch_alter_table('book', schema=None) as batch_op:
        batch_op.alter_column('isbn',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=20),
               existing_nullable=False)

    with op.batch_alter_table('librarian', schema=None) as batch_op:
        batch_op.add_column(sa.Column('alternative_id', sa.String(length=36), nullable=True))

    with op.batch_alter_table('student', schema=None) as batch_op:
        batch_op.add_column(sa.Column('alternative_id', sa.String(length=36), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student', schema=None) as batch_op:
        batch_op.drop_column('alternative_id')

    with op.batch_alter_table('librarian', schema=None) as batch_op:
        batch_op.drop_column('alternative_id')

    with op.batch_alter_table('book', schema=None) as batch_op:
        batch_op.alter_column('isbn',
               existing_type=sa.String(length=20),
               type_=sa.INTEGER(),
               existing_nullable=False)

    op.create_table('_alembic_tmp_book',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('total_copies', sa.INTEGER(), nullable=True),
    sa.Column('book_category_id', sa.INTEGER(), nullable=False),
    sa.Column('author_id', sa.INTEGER(), nullable=False),
    sa.Column('title', sa.VARCHAR(length=200), nullable=False),
    sa.Column('description', sa.VARCHAR(length=500), nullable=False),
    sa.Column('version', sa.VARCHAR(length=20), nullable=False),
    sa.Column('publisher', sa.VARCHAR(length=100), nullable=False),
    sa.Column('isbn', sa.VARCHAR(length=20), nullable=False),
    sa.Column('img_upload', sa.VARCHAR(length=100), nullable=False),
    sa.Column('available_copies', sa.INTEGER(), nullable=True),
    sa.Column('created_date', sa.DATETIME(), nullable=True),
    sa.Column('updated_date', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['author.id'], ),
    sa.ForeignKeyConstraint(['book_category_id'], ['book_category.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
