"""empty message

Revision ID: 278fe296c163
Revises: 7fc2c82dbd5b
Create Date: 2023-09-24 12:18:35.450741

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '278fe296c163'
down_revision = '7fc2c82dbd5b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fine', schema=None) as batch_op:
        batch_op.add_column(sa.Column('amounts', sa.Float(), nullable=True))
        batch_op.drop_column('amount')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fine', schema=None) as batch_op:
        batch_op.add_column(sa.Column('amount', sa.FLOAT(), nullable=True))
        batch_op.drop_column('amounts')

    # ### end Alembic commands ###
