"""empty message

Revision ID: 28bfe82e917e
Revises: 71669db31385
Create Date: 2023-09-03 10:35:47.870167

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '28bfe82e917e'
down_revision = '71669db31385'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student', schema=None) as batch_op:
        batch_op.alter_column('img_upload',
               existing_type=sa.FLOAT(),
               type_=sa.String(length=100),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student', schema=None) as batch_op:
        batch_op.alter_column('img_upload',
               existing_type=sa.String(length=100),
               type_=sa.FLOAT(),
               existing_nullable=False)

    # ### end Alembic commands ###
