"""empty message

Revision ID: 3a1dd06bb254
Revises: 6f6ec2e4b6e8
Create Date: 2023-09-18 13:25:34.235964

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3a1dd06bb254'
down_revision = '6f6ec2e4b6e8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student', schema=None) as batch_op:
        batch_op.add_column(sa.Column('alternative_id', sa.String(length=36), nullable=False))
        batch_op.drop_column('alternative_i')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student', schema=None) as batch_op:
        batch_op.add_column(sa.Column('alternative_i', sa.VARCHAR(length=36), nullable=False))
        batch_op.drop_column('alternative_id')

    # ### end Alembic commands ###
