"""empty message

Revision ID: 45d00e7a6657
Revises: 7eb02800e9bc
Create Date: 2023-09-18 13:15:38.131819

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '45d00e7a6657'
down_revision = '7eb02800e9bc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('librarian', schema=None) as batch_op:
        batch_op.add_column(sa.Column('alternative_id', sa.String(length=36), nullable=True))
        batch_op.drop_column('alternative_i')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('librarian', schema=None) as batch_op:
        batch_op.add_column(sa.Column('alternative_i', sa.VARCHAR(length=36), nullable=True))
        batch_op.drop_column('alternative_id')

    # ### end Alembic commands ###
