"""empty message

Revision ID: 467a1d9976f2
Revises: 1a9986bdccf5
Create Date: 2023-09-23 22:32:38.097274

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '467a1d9976f2'
down_revision = '1a9986bdccf5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fine', schema=None) as batch_op:
        batch_op.drop_column('alternative_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fine', schema=None) as batch_op:
        batch_op.add_column(sa.Column('alternative_id', sa.VARCHAR(length=36), nullable=False))

    # ### end Alembic commands ###
