"""empty message

Revision ID: 7eb02800e9bc
Revises: 04028ec6a9c8
Create Date: 2023-09-18 13:15:19.731911

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7eb02800e9bc'
down_revision = '04028ec6a9c8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('librarian', schema=None) as batch_op:
        batch_op.add_column(sa.Column('alternative_i', sa.String(length=36), nullable=True))
        batch_op.drop_column('alternative_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('librarian', schema=None) as batch_op:
        batch_op.add_column(sa.Column('alternative_id', sa.VARCHAR(length=36), nullable=True))
        batch_op.drop_column('alternative_i')

    # ### end Alembic commands ###
