"""empty message

Revision ID: 7fc2c82dbd5b
Revises: 467a1d9976f2
Create Date: 2023-09-23 23:56:42.595537

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7fc2c82dbd5b'
down_revision = '467a1d9976f2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('issue', schema=None) as batch_op:
        batch_op.alter_column('fine_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('issue', schema=None) as batch_op:
        batch_op.alter_column('fine_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
