"""empty message

Revision ID: 880386704702
Revises: 9aba9829ef76
Create Date: 2023-10-01 07:49:49.890535

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '880386704702'
down_revision = '9aba9829ef76'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fine', schema=None) as batch_op:
        batch_op.add_column(sa.Column('matric_no', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fine', schema=None) as batch_op:
        batch_op.drop_column('matric_no')

    # ### end Alembic commands ###
