"""empty message

Revision ID: a54d5ea4820d
Revises: 28bfe82e917e
Create Date: 2023-09-12 02:05:42.615846

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a54d5ea4820d'
down_revision = '28bfe82e917e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('book', schema=None) as batch_op:
        batch_op.add_column(sa.Column('total_copie', sa.Integer(), nullable=True))
        batch_op.drop_column('total_copies')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('book', schema=None) as batch_op:
        batch_op.add_column(sa.Column('total_copies', sa.INTEGER(), nullable=True))
        batch_op.drop_column('total_copie')

    # ### end Alembic commands ###
