"""empty message

Revision ID: ada88f0b732d
Revises: 278fe296c163
Create Date: 2023-09-24 12:18:59.911602

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ada88f0b732d'
down_revision = '278fe296c163'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fine', schema=None) as batch_op:
        batch_op.add_column(sa.Column('amount', sa.Float(), nullable=True))
        batch_op.drop_column('amounts')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fine', schema=None) as batch_op:
        batch_op.add_column(sa.Column('amounts', sa.FLOAT(), nullable=True))
        batch_op.drop_column('amount')

    # ### end Alembic commands ###
